Fix app crashes when adding many trees in quick succession
The change fixes the issue where the app crashes when trying to add new
trees in quick succession. The crash is caused by the IllegalArgument exception.
See the exception pasted below. The fix is to disable the add new tree
button as soon after the very first click is registered.

Due to potential sluggishness of writing the new tree data to db and rendering the map
fragment screen, a quick succession of clicks on Add tree button by the user triggers its onClick
listeners more than once which cause the navigation action mapsFragment to new tree graph to take place.
If the navigation action has already completed, the duplicate action to navigate to the same destination
throws the exception causing the app to crash.

Steps to reproduce the crash:
1. Add new tree from the app.
2. The camera activity is launched.
3. Take an image which starts the new tree fragment.
4. Click save button which saves the data to the db and takes you to map
fragment
5. Immediately click on add tree button several times.
6. After few repititions of the above steps, the app crashes.

Verification for the fix:
1. Repeat the same steps listed above to crash the app.
2. The add tree button is disabled after the very first click.
3. No crash occurs.

```
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.greenstand.android.TreeTracker.dev, PID: 22273
    java.lang.IllegalArgumentException: navigation destination
org.greenstand.android.TreeTracker.dev:id/action_mapsFragment_to_new_tree_graph
is unknown to this NavController
        at
androidx.navigation.NavController.navigate(NavController.java:789)
        at
androidx.navigation.NavController.navigate(NavController.java:730)
        at
androidx.navigation.NavController.navigate(NavController.java:716)
        at
androidx.navigation.NavController.navigate(NavController.java:907)
        at
org.greenstand.android.TreeTracker.fragments.MapsFragment.onClick(MapsFragment.kt:155)
        at android.view.View.performClick(View.java:7346)
        at android.widget.TextView.performClick(TextView.java:14177)
 ```